apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: of83trbij-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: of83trbij-go 
  name: of83trbij-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: of83trbij-go 
